CREATE PROCEDURE USP_LOADACCOUNT
AS
BEGIN
    SELECT USERNAME AS N'Tài khoản',DISPLAYNAME AS N'Tên hiển thị', PASSWORD AS N'Mật khẩu', TYPE AS N'Loại tài khoản' FROM ACCOUNT
END
GO

CREATE PROCEDURE USP_ADD_ACCOUNT
@USERNAME NVARCHAR(100),
@DISPLAYNAME NVARCHAR(100),
@PASSWORD NVARCHAR(100),
@TYPE NVARCHAR(100)
AS
BEGIN
    INSERT INTO ACCOUNT(USERNAME,DISPLAYNAME,PASSWORD,TYPE) VALUES (@USERNAME,@DISPLAYNAME,@PASSWORD,@TYPE)
END
GO

CREATE PROCEDURE USP_DEL_ACCOUNT
@USERNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM ACCOUNT WHERE USERNAME LIKE @USERNAME
END
GO

CREATE PROCEDURE USP_EDIT_ACCOUNT
@USERNAME NVARCHAR(100),
@DISPLAYNAME NVARCHAR(100),
@PASSWORD NVARCHAR(100),
@TYPE NVARCHAR(100),
@where_USERNAME NVARCHAR(100)
AS
BEGIN
    UPDATE ACCOUNT SET USERNAME = @USERNAME, DISPLAYNAME=@DISPLAYNAME, PASSWORD=@PASSWORD, TYPE=@TYPE WHERE USERNAME=@where_USERNAME
END
GO

CREATE PROCEDURE USP_LOAD_CUSTOMER
AS
BEGIN
    SELECT NAME AS N'Họ tên',BIRTH AS N'Ngày sinh',PHONENUMBER AS N'Số điện thoại',ADDRESS AS N'Địa chỉ' FROM CUSTOMER
END
GO

CREATE PROCEDURE USP_ADD_CUSTOMER
@NAME NVARCHAR(100),
@BIRTH NVARCHAR(100),
@PHONENUMBER NVARCHAR(100),
@ADDRESS NVARCHAR(100)
AS
BEGIN
    INSERT INTO CUSTOMER(NAME,BIRTH,PHONENUMBER,ADDRESS) VALUES (@NAME,@BIRTH,@PHONENUMBER,@ADDRESS)
END
GO

CREATE PROCEDURE USP_DEL_CUSTOMER
@NAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM CUSTOMER WHERE NAME LIKE @NAME
END
GO

CREATE PROCEDURE USP_EDIT_CUSTOMER
@NAME NVARCHAR(100),
@BIRTH NVARCHAR(100),
@PHONENUMBER NVARCHAR(100),
@ADDRESS NVARCHAR(100),
@where_NAME NVARCHAR(100)
AS
BEGIN
    UPDATE CUSTOMER SET NAME=@NAME, BIRTH=@BIRTH, PHONENUMBER=@PHONENUMBER, ADDRESS=@ADDRESS WHERE NAME=@where_NAME
END
GO

CREATE PROCEDURE USP_SEARCH_CUSTOMER
@NAME NVARCHAR(100)
AS
BEGIN
    SELECT NAME,BIRTH,PHONENUMBER,ADDRESS FROM DBO.CUSTOMER WHERE NAME LIKE @NAME+'%'
END
GO

CREATE PROCEDURE USP_LOAD_BOOK
AS
BEGIN
    SELECT ID AS N'Mã Sách',BOOKNAME AS N'Tên sách',RELEASEYEAR AS N'Năm phát hành',GENRES AS N'Thể loại',AUTHOR AS N'Tác giả',PUBLISHER AS N'Nhà phát hành', BOOKSELF AS N'Kệ sách',QUANTITY AS N'Số lượng' from BOOK
END
GO

CREATE PROCEDURE USP_ADD_BOOK
@BOOKNAME NVARCHAR(100),
@RELEASEYEAR NVARCHAR(100),
@GENRES NVARCHAR(100),
@AUTHOR NVARCHAR(100),
@PUBLISHER NVARCHAR(100),
@BOOKSELF NVARCHAR(100),
@QUANTITY NVARCHAR(100)
AS
BEGIN 
    INSERT INTO BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY) VALUES (@BOOKNAME,@RELEASEYEAR,@GENRES,@AUTHOR,@PUBLISHER,@BOOKNAME,@QUANTITY)
END
GO

CREATE PROCEDURE USP_DEL_BOOK
@ID INT
AS
BEGIN
    DELETE FROM BOOK WHERE ID LIKE @ID
END
GO

CREATE PROCEDURE USP_EDIT_BOOK
@BOOKNAME NVARCHAR(100),
@RELEASEYEAR NVARCHAR(100),
@GENRES NVARCHAR(100),
@AUTHOR NVARCHAR(100),
@PUBLISHER NVARCHAR(100),
@BOOKSELF NVARCHAR(100),
@QUANTITY NVARCHAR(100),
@where_BOOKNAME NVARCHAR(100)
AS
BEGIN
    UPDATE BOOK SET BOOKNAME=@BOOKNAME, RELEASEYEAR=@RELEASEYEAR, GENRES=@GENRES, AUTHOR=@AUTHOR, PUBLISHER=@PUBLISHER, BOOKSELF=@BOOKSELF, QUANTITY=@QUANTITY where BOOKNAME=@where_BOOKNAME
END
GO

CREATE PROCEDURE USP_SEARCH_BY_BOOKNAME
@BOOKNAME NVARCHAR(100)
AS
BEGIN
   SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE BOOKNAME LIKE @BOOKNAME+'%'
END
GO

CREATE PROCEDURE USP_SEARCH_BY_GENRES
@GENRES NVARCHAR(100)
AS
BEGIN
    SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE GENRES LIKE @GENRES+'%'
END
GO

CREATE PROCEDURE USP_SEARCH_BY_YEAR
@RELEASEYEAR NVARCHAR(100)
AS
BEGIN
    SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE RELEASEYEAR LIKE @RELEASEYEAR+'%'
END
GO

CREATE PROCEDURE USP_SEARCH_BY_AUTHOR
@AUTHOR NVARCHAR(100)
AS
BEGIN
    SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE AUTHOR LIKE @AUTHOR+'%'
END
GO

CREATE PROCEDURE USP_SEARCH_BY_PUBLISHER
@PUBLISHER NVARCHAR(100)
AS
BEGIN
    SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE PUBLISHER LIKE @PUBLISHER+'%'
END
GO

CREATE PROCEDURE USP_SEARCH_BY_BOOKSELF
@BOOKSELF NVARCHAR(100)
AS
BEGIN
    SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE BOOKSELF LIKE @BOOKSELF+'%'
END
GO

CREATE PROCEDURE USP_LOAD_CUSTOMER_NAME
AS
BEGIN
    SELECT NAME FROM CUSTOMER
END
GO

CREATE PROCEDURE USP_LOAD_BOOK_NAME
AS
BEGIN
    SELECT BOOKNAME FROM BOOK
END
GO

CREATE PROCEDURE USP_LOAD_BORROW
AS
BEGIN
    SELECT ID AS N'Mã phiếu', CUSTOMERNAME AS N'Tên khách hàng', BOOKNAME AS N'Tên sách', QUANTITY AS N'Số lượng', BORROWDATE AS N'Ngày mượn', PAIDDATE AS N'Ngày trả' FROM BORROW
END
GO

CREATE PROCEDURE USP_ADD_BOROW
@CUSTOMERNAME NVARCHAR(100),
@BOOKNAME NVARCHAR(100),
@QUANTITY NVARCHAR(100),
@BORROWDATE NVARCHAR(100),
@PAIDDATE NVARCHAR(100)
AS
BEGIN
    INSERT INTO BORROW(CUSTOMERNAME,BOOKNAME,QUANTITY,BORROWDATE,PAIDDATE) VALUES (@CUSTOMERNAME,@BOOKNAME,@QUANTITY,@BORROWDATE,@PAIDDATE)
END
GO
    
CREATE PROCEDURE USP_DEL_BOROW
@CUSTOMERNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM BORROW WHERE CUSTOMERNAME=@CUSTOMERNAME
END
GO

CREATE PROCEDURE USP_LOAD_LATEPAID
AS
BEGIN
    SELECT ID AS N'Mã phiếu',CUSTOMERNAME AS N'Tên khách hàng',BOOKNAME AS N'Tên sách', QUANTITY AS N'Số LƯỢNG', PAIDDATE AS N'Ngày trả', LATEPAIDDATE AS N'Ngày trả muộn', DAYLATE AS N'Số ngày trả muộn', BOOKLATE AS N'Số sách trả muộn', FEE AS N'Số tiền phạt' FROM LATEPAID
END
GO

CREATE PROCEDURE USP_ADD_LATEPAID
@CUSTOMERNAME NVARCHAR(100),
@BOOKNAME NVARCHAR(100),
@QUANTITY NVARCHAR(100),
@PAIDDATE NVARCHAR(100),
@LATEPAIDDATE NVARCHAR(100),
@DAYLATE NVARCHAR(100),
@BOOKLATE NVARCHAR(100),
@FEE NVARCHAR(100)
AS
BEGIN
    INSERT INTO dbo.LATEPAID(CUSTOMERNAME,BOOKNAME,QUANTITY,PAIDDATE,LATEPAIDDATE,DAYLATE,BOOKLATE,FEE) VALUES (@CUSTOMERNAME,@BOOKNAME,@QUANTITY,@PAIDDATE,@LATEPAIDDATE,@DAYLATE,@BOOKLATE,@FEE)
END
GO

CREATE PROCEDURE USP_DEL_LATEPAID
@CUSTOMERNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM LATEPAID WHERE CUSTOMERNAME=@CUSTOMERNAME
END
GO

CREATE PROCEDURE USP_LOGIN
@USERNAME NVARCHAR(100),
@PASSWORD NVARCHAR(100)
AS
BEGIN
    SELECT*FROM DBO.ACCOUNT WHERE USERNAME=@USERNAME AND PASSWORD=@PASSWORD
END
GO

CREATE PROCEDURE USP_LOAD_GENRES
AS
BEGIN
    SELECT GENRESNAME AS N'Thể loại' FROM GENRES
END
GO

CREATE PROCEDURE USP_ADD_GENRES
@GENRESNAME NVARCHAR(100)
AS
BEGIN
    INSERT INTO GENRES(GENRESNAME) VALUES (@GENRESNAME)
END
GO

CREATE PROCEDURE USP_DEL_GENRES
@GENRESNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM GENRES WHERE GENRESNAME=@GENRESNAME
END
GO

CREATE PROCEDURE USP_LOAD_AUTHOR
AS
BEGIN
    SELECT AUTHORNAME AS N'Tên tác giả', YEARDATE AS N'Năm sinh' FROM AUTHOR
END
GO

CREATE PROCEDURE USP_ADD_AUTHOR
@AUTHORNAME NVARCHAR(100),
@YEARDATE NVARCHAR(100)
AS
BEGIN
    INSERT INTO dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (@AUTHORNAME,@YEARDATE)
END
GO

CREATE PROCEDURE USP_DEL_AUTHOR
@AUTHORNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM AUTHOR WHERE AUTHORNAME=@AUTHORNAME
END
GO

CREATE PROCEDURE USP_ADD_PUBLISHER
AS
BEGIN 
    SELECT PUBLISHERNAME AS N'Tên nhà xuất bản', ADDRESS AS N'Địa chỉ', PHONENUMBER AS N'Số điện thoại' FROM PUBLISHER
END
GO

CREATE PROCEDURE USP_LOAD_PUBLISHER
@PUBLISHERNAME NVARCHAR(100),
@ADDRESS NVARCHAR(100),
@PHONENUMBER NVARCHAR(100)
AS
BEGIN
    INSERT INTO PUBLISHER(PUBLISHERNAME,ADDRESS,PHONENUMBER) VALUES (@PUBLISHERNAME,@ADDRESS,@PHONENUMBER)
END
GO

CREATE PROCEDURE USP_DEL_PUBLISHER
@PUBLISHERNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM PUBLISHER WHERE PUBLISHERNAME=@PUBLISHERNAME
END
GO

CREATE PROCEDURE USP_LOAD_BOOKSELF
AS
BEGIN
    SELECT BOOKSELFNAME AS N'Kệ sách' FROM dbo.BOOKSELF
END
GO

CREATE PROCEDURE USP_ADD_BOOKSELF
@BOOKSELFNAME NVARCHAR(100)
AS
BEGIN
    INSERT INTO BOOKSELF(BOOKSELFNAME) VALUES (@BOOKSELFNAME)
END
GO

CREATE PROCEDURE USP_DEL_BOOKSELF
@BOOKSELFNAME NVARCHAR(100)
AS
BEGIN
    DELETE FROM BOOKSELF WHERE BOOKSELFNAME = @BOOKSELFNAME
END
GO


EXEC USP_LOAD_GENRES
EXEC USP_LOAD_LATEPAID
EXEC USP_LOAD_BORROW
EXEC USP_LOAD_BOOK_NAME
EXEC DBO.USP_LOAD_CUSTOMER_NAME
EXEC DBO.USP_LOAD_BOOK
EXEC DBO.USP_LOAD_CUSTOMER
EXEC DBO.USP_LOADACCOUNT

DROP PROCEDURE USP_EDIT_BOOK
DROP PROCEDURE USP_LOAD_CUSTOMER
DROP PROCEDURE USP_ADD_CUSTOMER
DROP PROCEDURE USP_LOAD_BOOK
DROP PROCEDURE USP_DEL_BOOK
DROP PROCEDURE USP_ADD_BOOK
DROP PROCEDURE LOAD_CUSTOMER_NAME
DROP PROCEDURE USP_LOAD_BORROW
DROP PROCEDURE USP_LOAD_BOOKSELF