CREATE DATABASE QUANLYTHUvIEN
use QUANLYTHUvIEN
GO

USE QUANLYTHUVIEN
GO

--Quản lý sách
--Quản lý thể loại
--Quản lý tác giả
--Quản lý Nhà xuất bản
--Quản lý khách hàng
--Quản lý kệ sách
--Quản lý tài khoản
--Quản lý hóa đơn

CREATE TABLE ACCOUNT
(
      ID INT IDENTITY PRIMARY KEY,
	  DISPLAYNAME NVARCHAR(100) NOT NULL,
	  USERNAME NVARCHAR(100) NOT NULL,
	  PASSWORD NVARCHAR(100) NOT NULL,
	  TYPE NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE BOOK
(
      ID INT IDENTITY PRIMARY KEY,
	  BOOKNAME NVARCHAR(100) NOT NULL,
	  RELEASEYEAR NVARCHAR(100) NOT NULL,  
	  GENRES NVARCHAR(100) NOT NULL,
	  AUTHOR NVARCHAR(100) NOT NULL,
	  PUBLISHER NVARCHAR(100) NOT NULL,
	  BOOKSELF NVARCHAR(100) NOT NULL,
	  QUANTITY NVARCHAR(100) NOT NULL DEFAULT 0 
)
GO


      --GENRESID INT NOT NULL,
	  --AUTHORID INT NOT NULL,
	  --PUBLISHERID INT NOT NULL,
	  --BOOKSELFID INT NOT NULL,

	  --FOREIGN KEY (GENRESID) REFERENCES DBO.GENRES(ID),
	  --FOREIGN KEY (AUTHORID) REFERENCES DBO.AUTHOR(ID),
	  --FOREIGN KEY (PUBLISHERID) REFERENCES DBO.PUBLISHER(ID),
	  --FOREIGN KEY (BOOKSELFID) REFERENCES DBO.BOOKSELF(ID)


CREATE TABLE GENRES
(
      ID INT IDENTITY PRIMARY KEY,
	  GENRESNAME NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE AUTHOR
(
      ID INT IDENTITY PRIMARY KEY,
	  AUTHORNAME NVARCHAR(100) NOT NULL,
	  YEARDATE NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE PUBLISHER
(
      ID INT IDENTITY PRIMARY KEY,
	  PUBLISHERNAME NVARCHAR(100)NOT NULL,
	  ADDRESS NVARCHAR(100)NOT NULL,
	  PHONENUMBER NVARCHAR(100)NOT NULL,
)
GO

CREATE TABLE BOOKSELF
(
      ID INT IDENTITY PRIMARY KEY,
	  BOOKSELFNAME NVARCHAR(100)NOT NULL,
)

CREATE TABLE CUSTOMER
(
      ID INT IDENTITY PRIMARY KEY,
	  NAME NVARCHAR(100) NOT NULL,
	  BIRTH NVARCHAR(100) NOT NULL,
	  PHONENUMBER NVARCHAR(100) NOT NULL,
	  ADDRESS NVARCHAR(100) NOT NULL,
)
GO


CREATE TABLE BORROW
(
      ID INT IDENTITY PRIMARY KEY,
	  CUSTOMERNAME NVARCHAR(100) NOT NULL,
	  BOOKNAME NVARCHAR(100) NOT NULL,
	  QUANTITY NVARCHAR(100) NOT NULL,
	  BORROWDATE NVARCHAR(100) NOT NULL,
	  PAIDDATE NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE LATEPAID
(
      ID INT IDENTITY PRIMARY KEY,
	  CUSTOMERNAME NVARCHAR(100) NOT NULL,
	  BOOKNAME NVARCHAR(100) NOT NULL,
	  QUANTITY NVARCHAR(100) NOT NULL,
	  PAIDDATE NVARCHAR(100) NOT NULL,
	  LATEPAIDDATE NVARCHAR(100) NOT NULL,
	  DAYLATE NVARCHAR(100) NOT NULL,
	  BOOKLATE NVARCHAR(100) NOT NULL,
	  FEE NVARCHAR(100) NOT NULL,
)



INSERT dbo.ACCOUNT(USERNAME,DISPLAYNAME,PASSWORD,TYPE) VALUES(N'admin1',N'Quản lý 1',N'admin',N'Quản lý')
INSERT dbo.ACCOUNT(USERNAME,DISPLAYNAME,PASSWORD,TYPE) VALUES(N'admin2',N'Quản lý 2',N'admin',N'Quản lý')
INSERT dbo.ACCOUNT(USERNAME,DISPLAYNAME,PASSWORD,TYPE) VALUES(N'librarian1',N'Thủ thư 1',N'librarian',N'Thủ thư')
INSERT dbo.ACCOUNT(USERNAME,DISPLAYNAME,PASSWORD,TYPE) VALUES(N'librarian2',N'Thủ thư 2',N'librarian',N'Thủ thư')

INSERT dbo.CUSTOMER(NAME,BIRTH,PHONENUMBER,ADDRESS)VALUES(N'Nguyễn Đức Huy','2003-2-25','09284561861',N'17 Lê Lai')
INSERT dbo.CUSTOMER(NAME,BIRTH,PHONENUMBER,ADDRESS)VALUES(N'Hoàng Trọng Nghĩa ','2002-7-14','09254871465',N'65 Lê lợi')
INSERT dbo.CUSTOMER(NAME,BIRTH,PHONENUMBER,ADDRESS)VALUES(N'Đào Trọng Trinh','2003-8-19','09735462875',N'418 Lạch Tray')
INSERT dbo.CUSTOMER(NAME,BIRTH,PHONENUMBER,ADDRESS)VALUES(N'Phạm Trung Đức','2001-3-29','09273571243',N'28 Cầu Đất')
INSERT dbo.CUSTOMER(NAME,BIRTH,PHONENUMBER,ADDRESS)VALUES(N'Nguyễn Đình Minh','2003-11-17','09284561861',N'49 Tô Hiệu')

--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Chiến tranh tiền tệ','2022',1,1,3,1)--Kinh tế
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Phía sau nghi can X','2017',2,2,2,2)--Trinh Thám
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Hoàng đê Ceasar','2009',3,3,5,3)--Lịch sử
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Sự im lặng của bầy cừu','2021',2,4,5,1)--Trinh thám
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Lời hiện triệu Cthulhu','2022',4,5,4,4)--Kinh dị
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Thần thoại Hy Lạp','2007',5,6,1,5)--Thần thoại
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Thần thoại Bắc Âu','2015',5,10,3,5)--Thần thoại
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Thao túng tâm lý','2016',6,7,2,6)--Tâm lý học
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Nghệ thuật Graffiti','2019',7,8,3,7)--Mỹ thuật
--INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENSEID,AUTHORID,PUBLISHERID,BOOKSELFID) VALUES (N'Cái chết đen','2018',4,9,3,4)--Kinh dị

INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Chiến tranh tiền tệ',2022,N'Kinh tế',N'Tống Hồng Binh',N'NXB Lao động',N'A1')--Kinh tế
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Phía sau nghi can X',2017,N'Trinh thám',N'Higashino Keigo',N'NXB Trẻ',N'A2')--Trinh Thám
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Hoàng đê Ceasar',2009,N'Lịch sử',N'Philip Freeman',N'NXB Kim Đồng',N'A3')--Lịch sử
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Sự im lặng của bầy cừu',2021,N'Trinh thám',N'Thomas Harris',N'NXB Nhã Nam',N'A2')--Trinh thám
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Lời hiện triệu Cthulhu',2022,N'Kinh dị',N'HP Love Craft',N'NXB Thanh Niên',N'B1')--Kinh dị
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Thần thoại Hy Lạp',2007,N'Thần thoại',N'Thomas Bulfinch',N'NXB Lao động',N'B2')--Thần thoại
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Thần thoại Bắc Âu',2015,N'Thần thoại',N'Neil Gaiman',N'NXB Trẻ',N'B2')--Thần thoại
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Thao túng tâm lý',2016,N'Tâm lý học',N'Shannon Thomas',N'NXB Kim Đồng',N'B3')--Tâm lý học
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Nghệ thuật Graffiti',2019,N'Mỹ thuật',N'Thames Hudson',N'NXB Nhã Nam',N'C1')--Mỹ thuật
INSERT dbo.BOOK(BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF) VALUES (N'Cái chết đen',2018,N'Kinh dị',N'John Hatcher',N'NXB Thanh Niên',N'C2')--Kinh dị

INSERT dbo.GENRES(GENRESNAME) VALUES (N'Kinh tế')
INSERT dbo.GENRES(GENRESNAME) VALUES (N'Trinh Thám')
INSERT dbo.GENRES(GENRESNAME) VALUES (N'Lịch sử')
INSERT dbo.GENRES(GENRESNAME) VALUES (N'Kinh dị')
INSERT dbo.GENRES(GENRESNAME) VALUES (N'Thần thoại')
INSERT dbo.GENRES(GENRESNAME) VALUES (N'Tâm lý học')
INSERT dbo.GENRES(GENRESNAME) VALUES (N'Mỹ thuật')

INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Tống Hồng Binh',1987)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Higashino Keigo',1976)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Philip Freeman',1985)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Thomas Harris',1973)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'HP Love Craft',1914)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Thomas Bulfinch',1943)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Neil Gaiman',1984)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Shannon Thomas',1989)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'Thames Hudson',1995)
INSERT dbo.AUTHOR(AUTHORNAME,YEARDATE) VALUES (N'John Hatcher',1997)

INSERT dbo.PUBLISHER (PUBLISHERNAME,ADDRESS,PHONENUMBER) VALUES (N'NXB Lao động',N'Hà Nội','092837463723')
INSERT dbo.PUBLISHER (PUBLISHERNAME,ADDRESS,PHONENUMBER) VALUES (N'NXB Trẻ',N'Hà Nội','09827365417')
INSERT dbo.PUBLISHER (PUBLISHERNAME,ADDRESS,PHONENUMBER) VALUES (N'NXB Kim Đồng',N'Hà Nội','09283746416')
INSERT dbo.PUBLISHER (PUBLISHERNAME,ADDRESS,PHONENUMBER) VALUES (N'NXB Nhã Nam',N'Hải Phòng','02937462828')
INSERT dbo.PUBLISHER (PUBLISHERNAME,ADDRESS,PHONENUMBER) VALUES (N'NXB Thanh Niên',N'Hà Nội','09283412368')

INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'A1')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'A2')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'A3')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'B1')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'B2')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'B3')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'C1')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'C2')
INSERT DBO.BOOKSELF(BOOKSELFNAME) VALUES (N'C3')

INSERT dbo.BORROW(CUSTOMERNAME,BOOKNAME,QUANTITY,BORROWDATE,PAIDDATE) VALUES(N'Hoàng Trọng Nghĩa',N'Thần thoại Bắc Âu ',2,N'2023-5-25',N'2023-6-5')
INSERT dbo.BORROW(CUSTOMERNAME,BOOKNAME,QUANTITY,BORROWDATE,PAIDDATE) VALUES(N'Nguyễn Đức Huy',N'Phía sau nghi can X ',2,N'2023-4-14',N'2023-5-10')
INSERT dbo.BORROW(CUSTOMERNAME,BOOKNAME,QUANTITY,BORROWDATE,PAIDDATE) VALUES(N'Đào Trọng Trinh',N'Chiến tranh tiền tệ ',2,N'2023-5-30',N'2023-6-15')
INSERT dbo.BORROW(CUSTOMERNAME,BOOKNAME,QUANTITY,BORROWDATE,PAIDDATE) VALUES(N'abc',N'Chiến tranh tiền tệ ',2,N'2023-5-30',N'2023-6-15')


INSERT DBO.LATEPAID(CUSTOMERNAME,BOOKNAME,QUANTITY,PAIDDATE,LATEPAIDDATE,DAYLATE,BOOKLATE,FEE) VALUES (N'Hoàng Trọng Nghĩa',N'Thần thoại Bắc Âu',2,N'2023-6-5',N'2023-6-7',2,20000,40000)


ALTER TABLE ACCOUNT ADD DEFAULT(N'NO NAME')FOR DISPLAYNAME
GO

ALTER TABLE ACCOUNT ADD DEFAULT(N'00000')FOR PASSWORD
GO

ALTER TABLE ACCOUNT ADD DEFAULT(N'LIBRARIAN')FOR TYPE
GO

ALTER TABLE BOOK ADD FOREIGN KEY (GENSEID) REFERENCES GENRES (ID)
GO

ALTER TABLE BOOK ADD FOREIGN KEY (AUTHORID) REFERENCES AUTHOR (ID)
GO

ALTER TABLE BOOK ADD FOREIGN KEY (PUBLISHERID) REFERENCES PUBLISHER (ID)
GO

ALTER TABLE BOOK ADD FOREIGN KEY (BOOKSELFID) REFERENCES BOOKSELF (ID)
GO


SELECT ID, BOOKNAME,RELEASEYEAR,GENRES,AUTHOR,PUBLISHER,BOOKSELF,QUANTITY FROM dbo.BOOK WHERE GENRES LIKE N'Kinh tế'

















drop table dbo.BORROW
drop table dbo.PAID
drop table dbo.CUSTOMER
DROP TABLE DBO.BOOK

SELECT*FROM dbo.ACCOUNT
SeLECT*FROM dbo.AUTHOR
SELECT*FROM dbo.BOOKSELF
SELECT*FROM dbo.CUSTOMER
SELECT*FROM DBO.GENRES
SELECT*FROM DBO.PUBLISHER
SELECT*FROM DBO.BORROW
SELECT*FROM DBO.LATEPAID
SELECT*FROM dbo.BOOK


SELECT*FROM DBO.CUSTOMER WHERE NAME LIKE N'H%'

SELECT NAME,BIRTH,PHONENUMBER,ADDRESS FROM DBO.CUSTOMER WHERE NAME LIKE N'H%'


select * from dbo.BOOK WHERE DBO.BOOK.GENSEID=DBO.GENRES.ID

DROP TABLE DBO.BOOK
DROP TABLE DBO.GENRES
DROP TABLE DBO.AUTHOR
DROP TABLE DBO.PUBLISHER
DROP TABLE DBO.BOOKSELF

DROP TABLE BORROW
DROP TABLE LATEPAID

